name: Output event
on:
  issues:
    types: [opened, edited]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Render the Event information
        run: echo "${{ toJSON(github.event) }}"